//! Writes `games/racing/BALANCE.md`:
//! `cargo run -p racing --release --example balance -- 200` (deterministic; the
//! argument is the seed count for the field runs, solo runs always use 1,000 seeds).

use racing::balance::{field, mirror, mixed, solo, Field};
use racing::catalog::PRESETS;
use racing::drivers::{
    Behavior, BlockerParams, CutterParams, FollowerParams, CUTTER_GAP, CUTTER_PASS_ROOM,
};
use racing::Setup;
use std::fmt::Write;

const SOLO_SEEDS: u64 = 1000;

fn pct(a: usize, b: usize) -> f64 {
    if b == 0 {
        0.0
    } else {
        100.0 * a as f64 / b as f64
    }
}

fn ok(pass: bool) -> &'static str {
    if pass {
        "pass"
    } else {
        "**FAIL**"
    }
}

fn max_slot(f: &Field) -> (usize, usize) {
    let (slot, &wins) = f
        .wins_by_slot
        .iter()
        .enumerate()
        .max_by_key(|(_, w)| **w)
        .unwrap();
    (slot, wins)
}

fn main() {
    let n: u64 = std::env::args()
        .nth(1)
        .map_or(200, |s| s.parse().expect("seed count"));
    let mut md = String::new();
    let w = &mut md;
    writeln!(w, "# Racing balance report\n").unwrap();
    writeln!(
        w,
        "Generated by `cargo run -p racing --release --example balance -- {n}` (deterministic). \
         Track: the Ring, 3 laps, tick cap 3,600 (60 s). Solo runs use seeds 0..{SOLO_SEEDS}; \
         mirror and mixed runs use seeds 0..{n}. The seed moves only each driver's own jitter \
         (`games/racing/src/drivers/`) and, in mirror races, the grid order. Times are seconds at 60 ticks/s.\n"
    )
    .unwrap();

    // Runs.
    let solos: Vec<_> = Behavior::ALL
        .iter()
        .map(|&b| (b, solo(b, Setup::BALANCED, SOLO_SEEDS)))
        .collect();
    let mirrors: Vec<_> = Behavior::ALL
        .iter()
        .map(|&b| (b, field(&mirror(b, n))))
        .collect();
    let mixed = field(&mixed(n));

    // Acceptance.
    let solo_all = solos.iter().all(|(_, s)| s.finished == s.races);
    let fields: Vec<&Field> = mirrors.iter().map(|(_, f)| f).chain([&mixed]).collect();
    let fin = fields.iter().map(|f| f.finished).sum::<usize>();
    let entries = fields.iter().map(|f| f.entries).sum::<usize>();
    let capped = fields.iter().map(|f| f.capped).sum::<usize>();
    let races = fields.iter().map(|f| f.races).sum::<usize>();
    let medians: Vec<f64> = fields.iter().map(|f| f.median_s).collect();
    let med_ok = medians.iter().all(|m| (20.0..=40.0).contains(m));
    let solo_of = |b: Behavior| solos.iter().find(|(x, _)| *x == b).unwrap().1.clone();
    let (fs, cs) = (solo_of(Behavior::Follower), solo_of(Behavior::Cutter));
    let (best_driver, best_wins) = Behavior::ALL
        .iter()
        .zip(mixed.wins_by_driver)
        .max_by_key(|(_, w)| *w)
        .map(|(b, w)| (*b, w))
        .unwrap();
    let mirror_max = mirrors
        .iter()
        .map(|(b, f)| (b, max_slot(f), f.races))
        .max_by(|a, b| pct(a.1 .1, a.2).partial_cmp(&pct(b.1 .1, b.2)).unwrap())
        .unwrap();

    writeln!(w, "## 1. Acceptance (racing.md)\n").unwrap();
    writeln!(w, "| Target | Measured | Result |\n|---|---|---|").unwrap();
    writeln!(
        w,
        "| Each baseline finishes all 3 laps alone on {SOLO_SEEDS} seeds | {} | {} |",
        solos
            .iter()
            .map(|(b, s)| format!("{} {}/{}", b.name(), s.finished, s.races))
            .collect::<Vec<_>>()
            .join(", "),
        ok(solo_all)
    )
    .unwrap();
    writeln!(
        w,
        "| At least 95% finish in 4-car races | {fin}/{entries} car-races ({:.1}%) | {} |",
        pct(fin, entries),
        ok(pct(fin, entries) >= 95.0)
    )
    .unwrap();
    writeln!(
        w,
        "| Median 4-car race 20–40 s | {} | {} |",
        medians
            .iter()
            .map(|m| format!("{m:.2} s"))
            .collect::<Vec<_>>()
            .join(", ")
            + " (mirrors F/C/B, mixed)",
        ok(med_ok)
    )
    .unwrap();
    writeln!(
        w,
        "| Under 5% of races hit the tick cap | {capped}/{races} ({:.1}%) | {} |",
        pct(capped, races),
        ok(pct(capped, races) < 5.0)
    )
    .unwrap();
    writeln!(
        w,
        "| Cutter solo faster than Follower (median of {SOLO_SEEDS}) | Cutter {:.2} s vs Follower {:.2} s | {} |",
        cs.median_s,
        fs.median_s,
        ok(cs.median_s < fs.median_s)
    )
    .unwrap();
    writeln!(
        w,
        "| Mixed 4-car, {n} seeds with grid rotation: no baseline wins more than 70% | {} wins {best_wins}/{} ({:.1}%) | {} |",
        best_driver.name(),
        mixed.races,
        pct(best_wins, mixed.races),
        ok(pct(best_wins, mixed.races) <= 70.0)
    )
    .unwrap();
    writeln!(
        w,
        "| No grid slot wins more than 60% of mirror races | {} mirror, slot {}: {}/{} ({:.1}%) | {} |\n",
        mirror_max.0.name(),
        mirror_max.1 .0,
        mirror_max.1 .1,
        mirror_max.2,
        pct(mirror_max.1 .1, mirror_max.2),
        ok(pct(mirror_max.1 .1, mirror_max.2) <= 60.0)
    )
    .unwrap();

    writeln!(w, "## 2. Solo, 3-3-3, {SOLO_SEEDS} seeds\n").unwrap();
    writeln!(
        w,
        "| Driver | Finished | Median | Best | Worst |\n|---|---|---|---|---|"
    )
    .unwrap();
    for (b, s) in &solos {
        writeln!(
            w,
            "| {} | {}/{} | {:.2} s | {:.2} s | {:.2} s |",
            b.name(),
            s.finished,
            s.races,
            s.median_s,
            s.best_s,
            s.worst_s
        )
        .unwrap();
    }

    writeln!(
        w,
        "\n## 3. Mirror races: 4 of one driver, 3-3-3, grid order shuffled by seed, {n} seeds\n"
    )
    .unwrap();
    writeln!(
        w,
        "| Driver | Finished | Median race | Capped | Wins by slot 0/1/2/3 | Top slot |\n|---|---|---|---|---|---|"
    )
    .unwrap();
    for (b, f) in &mirrors {
        let (s, ws) = max_slot(f);
        writeln!(
            w,
            "| {} | {}/{} | {:.2} s | {} | {} | slot {s} {:.1}% |",
            b.name(),
            f.finished,
            f.entries,
            f.median_s,
            f.capped,
            f.wins_by_slot.map(|x| x.to_string()).join(" / "),
            pct(ws, f.races)
        )
        .unwrap();
    }

    writeln!(
        w,
        "\n## 4. Mixed races, 3-3-3, {n} seeds\n\nLineups Follower, Cutter, Blocker plus a fourth car that is each driver in turn; \
         each lineup runs on all 4 grid rotations, so 12 races per seed and every driver drives the same number of car-races.\n"
    )
    .unwrap();
    writeln!(
        w,
        "| Driver | Entries | Wins | Win share of races |\n|---|---|---|---|"
    )
    .unwrap();
    for (i, b) in Behavior::ALL.iter().enumerate() {
        writeln!(
            w,
            "| {} | {} | {} | {:.1}% |",
            b.name(),
            mixed.entries_by_driver[i],
            mixed.wins_by_driver[i],
            pct(mixed.wins_by_driver[i], mixed.races)
        )
        .unwrap();
    }
    writeln!(
        w,
        "\nFinished {}/{} car-races, median race {:.2} s, {} capped. Wins by grid slot 0/1/2/3: {} (info; the 60% slot cap applies to mirrors).\n",
        mixed.finished,
        mixed.entries,
        mixed.median_s,
        mixed.capped,
        mixed.wins_by_slot.map(|x| x.to_string()).join(" / ")
    )
    .unwrap();

    writeln!(w, "## 5. Setups, solo, {n} seeds (info)\n").unwrap();
    writeln!(w, "Median solo time per catalog preset. R4's evolution tunes the setup with the driver params.\n").unwrap();
    writeln!(
        w,
        "| Preset | Setup | Follower | Cutter | Blocker |\n|---|---|---|---|---|"
    )
    .unwrap();
    for (_, label, setup) in PRESETS {
        let cells: Vec<String> = Behavior::ALL
            .iter()
            .map(|&b| {
                let s = solo(b, setup, n);
                if s.finished == s.races {
                    format!("{:.2} s", s.median_s)
                } else {
                    format!("{:.2} s ({}/{} finish)", s.median_s, s.finished, s.races)
                }
            })
            .collect();
        writeln!(w, "| {label} | {setup} | {} |", cells.join(" | ")).unwrap();
    }

    let phys = racing::Physics::default();
    let (fp, cp, bp) = (
        FollowerParams::default(),
        CutterParams::default(),
        BlockerParams::default(),
    );
    writeln!(w, "\n## 6. Values: first cut → tuned\n").unwrap();
    writeln!(
        w,
        "Hand-maintained text, printed by the example. Physics is unchanged from R1.\n"
    )
    .unwrap();
    writeln!(
        w,
        "| Value | R2 first cut | Tuned (shipped) |\n|---|---|---|"
    )
    .unwrap();
    writeln!(w, "| Braking (u/s²) | 480 | {} (kept) |", phys.brake).unwrap();
    writeln!(w, "| Follower look-ahead / corner speed / braking distance | 70 u / 160 u/s / 20 u | {} u / {} u/s / {} u |", fp.look_ahead, fp.corner_speed, fp.brake_distance).unwrap();
    writeln!(w, "| Cutter apex margin / entry speed / exit point | 46 u / 128 u/s / 90 u | {} u / {} u/s / {} u (kept) |", cp.apex_margin, cp.entry_speed, cp.exit_point).unwrap();
    writeln!(w, "| Cutter in traffic | passes like the Follower, half the offset | lifts behind a car within {CUTTER_GAP} u (or alongside); passes only with {CUTTER_PASS_ROOM} u of straight |").unwrap();
    writeln!(w, "| Blocker corner speed / block distance / block strength | 160 u/s / 120 u / 1.0 | {} u/s / {} u / {} |", bp.follower.corner_speed, bp.block_distance, bp.block_strength).unwrap();
    writeln!(
        w,
        "\nWhy: with the first-cut values the Cutter won 93% of mixed races (2,242 of 2,400) despite a solo edge of about 1%: \
         it took the lead from any slot in the first corners by diving inside, and the others never got it back. \
         Making it patient in traffic brought that to the table above. The Blocker's blocking costs it more time than it \
         gains (it wins fewer mixed races with blocking on than off), so the block was shortened and softened and its corner \
         speed raised; it is the weakest baseline in traffic, not the strongest as racing.md intends. That's a known gap for R4's \
         evolution, not an acceptance target.\n"
    )
    .unwrap();

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/BALANCE.md");
    std::fs::write(path, md).expect("write BALANCE.md");
    println!("wrote {path}");
}
