//! Tank Arena balance report (SPEC "Acceptance (customization)" and "Scripted policies").
//!
//! 1. Policy triangle at 3/3/3: kiter > charger > sniper > kiter, every pairing 55–80%
//!    over 200 mirrored seeds.
//! 2. Loadouts: per policy, every one of the 19 loadouts plays every one of the 19
//!    (same policy both sides, so the build is the only difference) over 200 mirrored
//!    seeds; no loadout may win more than 70% averaged across its 19 opponents.
//!
//! "Mirrored seeds": each seed is played twice with the sides swapped. Win rate =
//! wins / games (draws count as not winning). Deterministic: same code, same numbers.
//!
//! `cargo run -p tank --release --example balance -- [seeds] > games/tank/BALANCE.md`

use std::sync::atomic::{AtomicUsize, Ordering};
use std::thread;
use tank::{Behavior, Loadout, MatchSpec, TankSpec};

#[derive(Clone, Copy, Default)]
struct Tally {
    wins: u32,
    losses: u32,
    draws: u32,
}

impl Tally {
    fn games(&self) -> u32 {
        self.wins + self.losses + self.draws
    }
    fn rate(&self) -> f64 {
        100.0 * self.wins as f64 / self.games().max(1) as f64
    }
}

/// `a` vs `b` over `seeds` mirrored seeds, from `a`'s side; also the match ticks.
fn duel(a: TankSpec, b: TankSpec, seeds: u64) -> (Tally, Vec<u32>) {
    let mut t = Tally::default();
    let mut ticks = Vec::with_capacity(2 * seeds as usize);
    for seed in 0..seeds {
        let m = MatchSpec {
            seed,
            blue: a,
            orange: b,
        };
        for (spec, a_team) in [(m, 0u8), (m.swapped(), 1u8)] {
            let (o, _) = spec.run();
            ticks.push(o.ticks);
            match o.winner {
                Some(w) if w == a_team => t.wins += 1,
                Some(_) => t.losses += 1,
                None => t.draws += 1,
            }
        }
    }
    (t, ticks)
}

/// Run `jobs` on all cores, keeping results in job order.
fn par_map<J: Sync, R: Send + Default + Clone>(jobs: &[J], f: impl Fn(&J) -> R + Sync) -> Vec<R> {
    let next = AtomicUsize::new(0);
    let n = thread::available_parallelism().map_or(4, |n| n.get());
    let mut out = vec![R::default(); jobs.len()];
    let chunks: Vec<Vec<(usize, R)>> = thread::scope(|s| {
        let hs: Vec<_> = (0..n)
            .map(|_| {
                s.spawn(|| {
                    let mut mine = Vec::new();
                    loop {
                        let i = next.fetch_add(1, Ordering::Relaxed);
                        if i >= jobs.len() {
                            break mine;
                        }
                        mine.push((i, f(&jobs[i])));
                    }
                })
            })
            .collect();
        hs.into_iter().map(|h| h.join().expect("worker")).collect()
    });
    for (i, r) in chunks.into_iter().flatten() {
        out[i] = r;
    }
    out
}

fn median(v: &mut [u32]) -> f64 {
    v.sort_unstable();
    v[v.len() / 2] as f64 / 60.0
}

fn main() {
    let seeds: u64 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(200);
    let d = Loadout::DEFAULT;
    let mut all_ok = true;

    println!("# Tank Arena balance report\n");
    println!("Generated by `cargo run -p tank --release --example balance -- {seeds}` (deterministic). Seeds 0..{seeds}, each played twice with sides swapped (\"mirrored\"). Win rate = wins / games; draws count as not winning. Policies use their default params (`games/tank/src/policies/`); tanks use the SPEC level tables (`games/tank/src/loadout.rs`).\n");

    // 1. Triangle.
    println!("## 1. Policy triangle at 3/3/3\n");
    println!(
        "SPEC: kiter > charger > sniper > kiter; every pairing 55–80% over 200 mirrored seeds.\n"
    );
    println!("| Pairing | Games | W | L | D | Win % | Median length | Pass |");
    println!("|---|---|---|---|---|---|---|---|");
    let pairs = [
        (Behavior::Kiter, Behavior::Charger),
        (Behavior::Charger, Behavior::Sniper),
        (Behavior::Sniper, Behavior::Kiter),
    ];
    let tri = par_map(&pairs, |&(a, b)| {
        duel(TankSpec::new(a, d), TankSpec::new(b, d), seeds)
    });
    let mut all_ticks = Vec::new();
    let mut draws = 0;
    let mut games = 0;
    for ((a, b), (t, ticks)) in pairs.iter().zip(tri) {
        let ok = (55.0..=80.0).contains(&t.rate());
        all_ok &= ok;
        let mut tk = ticks.clone();
        println!(
            "| {} > {} | {} | {} | {} | {} | {:.1}% | {:.1} s | {} |",
            a.name(),
            b.name(),
            t.games(),
            t.wins,
            t.losses,
            t.draws,
            t.rate(),
            median(&mut tk),
            if ok { "yes" } else { "**NO**" }
        );
        all_ticks.extend(ticks);
        draws += t.draws;
        games += t.games();
    }
    let med = median(&mut all_ticks);
    println!(
        "\nAcross the triangle: median match {med:.1} s, draws {:.1}%. SPEC targets median 30–60 s ({}) and < 10% draws ({}).\n",
        100.0 * draws as f64 / games as f64,
        if (30.0..=60.0).contains(&med) { "met" } else { "**not met**" },
        if (draws as f64) < 0.1 * games as f64 { "met" } else { "**not met**" },
    );

    // 2. Loadouts.
    println!("## 2. Loadouts (per policy, all 19 × 19)\n");
    println!("SPEC: no single loadout wins > 70% averaged across all 19 opponent loadouts (per policy, 200 mirrored seeds per pairing). Same policy on both sides. Averages include the mirror pairing (a loadout against itself).\n");
    let jobs: Vec<(Behavior, Loadout, Loadout)> = Behavior::ALL
        .iter()
        .flat_map(|&b| {
            Loadout::ALL
                .iter()
                .flat_map(move |&x| Loadout::ALL.iter().map(move |&y| (b, x, y)))
        })
        .collect();
    let res = par_map(&jobs, |&(b, x, y)| {
        duel(TankSpec::new(b, x), TankSpec::new(b, y), seeds)
    });
    let mut summary = Vec::new();
    for (bi, b) in Behavior::ALL.iter().enumerate() {
        println!("### {}\n", b.name());
        println!("| Loadout (A-S-D) | Avg win % | Best matchup | Worst matchup | Pass |");
        println!("|---|---|---|---|---|");
        let mut rows = Vec::new();
        for (xi, x) in Loadout::ALL.iter().enumerate() {
            let row: Vec<(Loadout, f64)> = (0..19)
                .map(|yi| (Loadout::ALL[yi], res[bi * 361 + xi * 19 + yi].0.rate()))
                .collect();
            let avg = row.iter().map(|r| r.1).sum::<f64>() / 19.0;
            let best = row
                .iter()
                .copied()
                .max_by(|a, b| a.1.total_cmp(&b.1))
                .unwrap();
            let worst = row
                .iter()
                .copied()
                .min_by(|a, b| a.1.total_cmp(&b.1))
                .unwrap();
            rows.push((*x, avg, best, worst));
        }
        rows.sort_by(|a, b| b.1.total_cmp(&a.1));
        for (x, avg, best, worst) in &rows {
            let ok = *avg <= 70.0;
            all_ok &= ok;
            println!(
                "| {x} | {avg:.1}% | vs {} {:.0}% | vs {} {:.0}% | {} |",
                best.0,
                best.1,
                worst.0,
                worst.1,
                if ok { "yes" } else { "**NO**" }
            );
        }
        let top = rows[0];
        summary.push((b.name(), top.0, top.1));
        let mine = &res[bi * 361..(bi + 1) * 361];
        let (dr, gm) = mine
            .iter()
            .fold((0, 0), |(d, g), (t, _)| (d + t.draws, g + t.games()));
        let mut tk: Vec<u32> = mine.iter().flat_map(|(_, v)| v.iter().copied()).collect();
        println!(
            "\n{} mirror matches (informational, not a SPEC target): median {:.1} s, draws {:.1}%.",
            b.name(),
            median(&mut tk),
            100.0 * dr as f64 / gm as f64
        );
        println!();
    }
    println!("## Verdict\n");
    for (b, x, avg) in &summary {
        println!(
            "- {b}: strongest loadout {x} at {avg:.1}% average ({}).",
            if *avg <= 70.0 {
                "≤ 70%, pass"
            } else {
                "> 70%, **fail**"
            }
        );
    }
    println!(
        "\n**{}**",
        if all_ok {
            "All balance acceptance checks pass."
        } else {
            "Some balance acceptance checks FAIL (marked above)."
        }
    );
    eprintln!("balance: {}", if all_ok { "PASS" } else { "FAIL" });
    std::process::exit(if all_ok { 0 } else { 1 });
}
